dist: xenial

language: node_js

node_js: "10"

install:
  - yarn install

script:
  - yarn workspaces run build
  - yarn workspaces run pack

deploy:
  provider: script
  script: bash scripts/deploy.sh
  skip_cleanup: true
  on:
    tags: true
    branch: master
    condition: tag =~ ^[0-9.]+
