dist: xenial

language: node_js

node_js: "10"

install: yarn install

script: yarn workspaces run build

deploy:
  provider: script
  script:
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build --build-arg BUILD_VERSION=$DOCKER_TAG -t travis-ci-build-stages-demo .
  - docker push $DOCKER_USERNAME/travis-ci-build-stages-demo
  on:
    tags: true
    condition: tag =~ ^[0-9.]+
