import fontawesome from '@fortawesome/fontawesome';

import * as faBook from '@fortawesome/fontawesome-free-solid/faBook';
import * as faSlidersH from '@fortawesome/fontawesome-free-solid/faSlidersH';
import * as faSuperscript from '@fortawesome/fontawesome-free-solid/faSuperscript';
import * as faCogs from '@fortawesome/fontawesome-free-solid/faCogs';
import * as faMicrochip from '@fortawesome/fontawesome-free-solid/faMicrochip';
import * as faDesktop from '@fortawesome/fontawesome-free-solid/faDesktop';
import * as faTerminal from '@fortawesome/fontawesome-free-solid/faTerminal';
import * as faHeartbeat from '@fortawesome/fontawesome-free-solid/faHeartbeat';
import * as faTachometerAlt from '@fortawesome/fontawesome-free-solid/faTachometerAlt';
import * as faRss from '@fortawesome/fontawesome-free-solid/faRss';
import * as faPowerOff from '@fortawesome/fontawesome-free-solid/faPowerOff';
import * as faCamera from '@fortawesome/fontawesome-free-solid/faCamera';
import * as faDatabase from '@fortawesome/fontawesome-free-solid/faDatabase';
import * as faExchangeAlt from '@fortawesome/fontawesome-free-solid/faExchangeAlt';
import * as faTimes from '@fortawesome/fontawesome-free-solid/faTimes';
import * as faEject from '@fortawesome/fontawesome-free-solid/faEject';
import * as faPlay from '@fortawesome/fontawesome-free-solid/faPlay';
import * as faPause from '@fortawesome/fontawesome-free-solid/faPause';
import * as faStop from '@fortawesome/fontawesome-free-solid/faStop';

fontawesome.library.add(faBook);
fontawesome.library.add(faSlidersH);
fontawesome.library.add(faSuperscript);
fontawesome.library.add(faCogs);
fontawesome.library.add(faMicrochip);
fontawesome.library.add(faDesktop);
fontawesome.library.add(faTerminal);
fontawesome.library.add(faHeartbeat);
fontawesome.library.add(faTachometerAlt);
fontawesome.library.add(faRss);
fontawesome.library.add(faPowerOff);
fontawesome.library.add(faCamera);
fontawesome.library.add(faDatabase);
fontawesome.library.add(faExchangeAlt);
fontawesome.library.add(faTimes);
fontawesome.library.add(faEject);
fontawesome.library.add(faPlay);
fontawesome.library.add(faPause);
fontawesome.library.add(faStop);
